version: '3'
services:
  postgres-db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: axon
      POSTGRES_DB: axon
      POSTGRES_PASSWORD: axon
  mongo-db:
    image: mongo:4.2
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: test
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    links:
      - 'mongo-db:mongo'
    ports:
      - 8081:8081
